---
AWSTemplateFormatVersion: "2010-09-09"
Description: This template creates all the necessary resources to run audio voice analysis (qs-1r0eejdoc).

Metadata:
  QuickStartDocumentation:
    EntrypointName: "Parameters for launching Call Center Intelligence Post-call Analytics"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Call Center Intelligence Post-call Analytics configuration
        Parameters:
          - CustomVocabularyName
          - UserPoolName
          - UserPoolDomainName
          - IdentityPoolName
          - UserPolicyName
          - AllowedOrigins
          - NotificationEmail
          - AgentChannel
          - AgentSpeakerLabel
          - CallResolutionClassifierName
          - CallMotivationClassifierName
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
      CustomVocabularyName:
        default: Custom vocabulary name
      UserPoolName:
        default: User pool name
      UserPoolDomainName:
        default: User pool domain name
      IdentityPoolName:
        default: Identity pool name
      UserPolicyName:
        default: User policy name
      QuickSightUserRoleName:
        default: QuickSight user role name
      AllowedOrigins:
        default: Allowed origins
      NotificationEmail:
        default: Contact email
      AgentChannel:
        default: Agent channel for multi-channel audio
      AgentSpeakerLabel:
        default: Agent speaker label for single-channel audio
      CallResolutionClassifierName:
        default: Display name of the call resolution classifier in Amazon Comprehend
      CallMotivationClassifierName:
        default: Display name of the call motivation classifier in Amazon Comprehend
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      ModeOfOperation:
        default: Audio File or Metadata
      MetadataOrAudioSuffix:
        default: Suffix for target file
      AudioFileJsonPath: 
        default: path to audio file if in metadata mode
      
Parameters:
  AgentChannel:
    Type: Number
    Default: 0
    Description: Left(0) or Right(1). Customer is set to the other channel.
  AgentSpeakerLabel:
    Type: Number
    Default: 0
    Description: First speaker(0) or last speaker(1). Customer is set to the other label.
  CustomVocabularyName: 
    Type: String
    Default: custom-vocabulary
    Description: Name of the Amazon Transcribe custom vocabulary.
  UserPoolName:
    Type: String
    Default: MyUserPool
    Description: Amazon Cognito user pool name.
  UserPoolDomainName:
    Type: String
    Default: icc-domain
    Description: Amazon Cognito user pool domain name. This value must be globally unique for a successful deployment. 
  IdentityPoolName:
    Type: String
    Default: MyIdentityPool
    Description: Amazon Cognito identiy pool name.
  UserPolicyName:
    Type: String
    Default: MyUserPolicy
    Description: Name of the user policy.
  AllowedOrigins:
    Type: String
    Default: '*'
    Description: Allowed origins for the portal website.
  DefaultRoot:
    Description: Default path for the index document.
    Type: String
    Default: index.html
  ErrorPage:
    Description: Path of the error page for the portal website.
    Type: String
    Default: error.html
  QuickSightUserRoleName:
    Type: String
    Default: QuickSightUserRole
    Description: IAM role name for the Amazon QuickSight user.
  CallResolutionClassifierName:
    Type: String
    Default: call-resolution
    Description: Name of the call resolution classifier.
  CallMotivationClassifierName:
    Type: String
    Default: call-motivation
    Description: Name of the call motivation classifier.
  NotificationEmail:
    Type: String
    Default: 'test@example.com'
    AllowedPattern: '^[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$'
    Description: Email address used for the notifications.
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: S3 bucket name for the Quick Start assets. Quick Start S3 bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
    Default: aws-quickstart
  QSS3KeyPrefix:
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), dots (.) and forward slash (/). The prefix should end with a forward slash (/).
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), dots
      (.), and forward slash (/). Prefix must end with a forward slash (/).
    Type: String
    Default: quickstart-onica-cci-postcall-analytics/
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  ModeOfOperation:
    Type: String
    Description: The Mode of Operation( AUDIO or METADATA)
    Default: 'AUDIO'
  MetadataOrAudioSuffix:
    Type: String
    Description: The suffix for the target metadata or audio file
    Default: ''
  AudioFileJsonPath:
    Type: String
    Description: Json path to audio file in metadata if in metadata mode
    Default: ''

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']

Resources:
  CopyArtifactsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/qs-artifacts.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketName: !Ref QSS3BucketName

  PostCallAnalyticsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/main.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        QSS3BucketName: !GetAtt CopyArtifactsStack.Outputs.DeploymentArtifactS3BucketName
        QSS3KeyPrefix: !GetAtt CopyArtifactsStack.Outputs.DeploymentArtifactS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion
        CustomVocabularyName: !Ref CustomVocabularyName
        UserPoolName: !Ref UserPoolName
        UserPoolDomainName: !Ref UserPoolDomainName
        IdentityPoolName: !Ref IdentityPoolName
        QuickSightUserRoleName: !Ref QuickSightUserRoleName
        UserPolicyName: !Ref UserPolicyName
        AllowedOrigins: !Ref AllowedOrigins
        DefaultRoot: !Ref DefaultRoot
        ErrorPage: !Ref ErrorPage
        CallResolutionClassifierName: !Ref CallResolutionClassifierName
        CallMotivationClassifierName: !Ref CallMotivationClassifierName
        NotificationEmail: !Ref NotificationEmail
        AgentChannel: !Ref AgentChannel
        AgentSpeakerLabel: !Ref AgentSpeakerLabel
        ModeOfOperation: !Ref ModeOfOperation
        MetadataOrAudioSuffix: !Ref MetadataOrAudioSuffix
        AudioFileJsonPath: !Ref AudioFileJsonPath

Outputs:
  CustomVocabularyName:
    Value: !Ref CustomVocabularyName
  UserPoolName:
    Value: !Ref UserPoolName
  IdentityPoolName:
    Value: !Ref IdentityPoolName
  QuickSightUserRoleName:
    Value: !Ref QuickSightUserRoleName
  UserPolicyName:
    Value: !Ref UserPolicyName
  AllowedOrigins:
    Value: !Ref AllowedOrigins
  PortalEndpoint:
    Value: !GetAtt PostCallAnalyticsStack.Outputs.PortalEndpoint