---
AWSTemplateFormatVersion: "2010-09-09"
Description: Creates authorizer resources (qs-1r0eejdq9)
Resources:   
  ComprehendCallResolutionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join: 
          - ''
          - - comprehend-call-resolution
            - -${self:provider.stage}-
            - Ref: ServicePrefix
  ComprehendCallMotivationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join: 
          - ''
          - - comprehend-call-motivation 
            - -${self:provider.stage}-
            - Ref: ServicePrefix

  TranscriptionOutput:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join: 
          - ''
          - - transcription-output 
            - -${self:provider.stage}-
            - Ref: ServicePrefix
  AudioFilesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join:
          - ''
          - - audio-files-queue
            - -${self:provider.stage}-
            - Ref: ServicePrefix
  TranscriptionAudioFiles:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - ''
          - - transcription-audio-files
            - -${self:provider.stage}-
            - Ref: ServicePrefix
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods: 
              - PUT
            AllowedOrigins: 
              - '*'

  StatusTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Join: 
          - ''
          - - jobStatus
            - -${self:provider.stage}-
            - Ref: ServicePrefix
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
        - AttributeName: audioURI
          AttributeType: S
        - AttributeName: transcriptURI
          AttributeType: S
        - AttributeName: lastModified
          AttributeType: S
        - AttributeName: transcriptionJobName
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
        - AttributeName: lastModified
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: audioLSI
          KeySchema:
            - AttributeName: jobId
              KeyType: HASH
            - AttributeName: audioURI
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: transcriptLSI
          KeySchema:
            - AttributeName: jobId
              KeyType: HASH
            - AttributeName: transcriptURI
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: jobStatusGSI
          KeySchema:
            - AttributeName: transcriptionJobName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  SplitTranscriptOutput:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join: 
          - ''
          - - split-transcript-output
            - -${self:provider.stage}-
            - Ref: ServicePrefix
  TextAnalysisOutput:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - ''
          - - text-analysis-output
            - -${self:provider.stage}-
            - Ref: ServicePrefix

  TranscriptionAudioFilesPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Join:
          - ''
          - - get-presignedurl-policy
            - -${self:provider.stage}-
            - Ref: ServicePrefix
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:Put*'
              - 's3:ListBucket'
              - 's3:Get*'
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - transcription-audio-files-${self:provider.stage}-
                    - Ref: ServicePrefix
              - Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - transcription-audio-files-${self:provider.stage}-
                    - Ref: ServicePrefix
                    - '/*'
  TextAnalysisPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Join:
          - ''
          - - text-analysis-policy
            - -${self:provider.stage}-
            - Ref: ServicePrefix
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:Put*'
              - 's3:ListBucket'
              - 's3:Get*'
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - text-analysis-output-${self:provider.stage}-
                    - Ref: ServicePrefix
              - Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - text-analysis-output-${self:provider.stage}-
                    - Ref: ServicePrefix
                    - '/*'
  TextAnalysisDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: 
          Fn::Join: 
            - ''
            - - text_analysis_database
              - -${self:provider.stage}-
              - Ref: ServicePrefix
        Description: "AWS Glue container to hold metadata tables for the text analysis crawler"
  TextAnalysisMetadataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: 
        Fn::Join: 
          - ''
          - - text-analysis-metadata-crawler
            - -${self:provider.stage}-
            - Ref: ServicePrefix      
      Role: !GetAtt TextAnalysisResultCrawlerRole.Arn
      #Classifiers: none, use the default classifier
      Description: AWS Glue crawler to crawl text analysis results
      Schedule: 
        ScheduleExpression: cron(0/59 * * * ? *)
      DatabaseName: !Ref TextAnalysisDatabase
      Targets:
        S3Targets:
          - Path: !Ref TextAnalysisOutput
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"
  TextAnalysisAthena:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Join: 
          - ''
          - - text-analysis-athena-results
            - -${self:provider.stage}-
            - Ref: ServicePrefix

  FetchTurnByTurnSentimentsNamedQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: !Ref TextAnalysisDatabase
      Description: "A query that selects turn by turn sentiments"
      Name: "Select Turn by turn sentiments"
      QueryString:
        Fn::Join:
          - ''
          - - 'WITH dataset AS (
              select asset_id as id, call_resolution_status as resolution, call_motivation_status as motivation, turns
              from '
            - '"text_analysis_database-${self:provider.stage}-'
            - Ref: ServicePrefix
            - '"."'
            - 'text_analysis_output_${self:provider.stage}_'
            - !Join ["_", !Split ["-", !Ref ServicePrefix] ]
            - '"'
            - ') select id, turn.turn, turn.channel, resolution, motivation, turn.sentiment.Sentiment, turn.sentiment.SentimentScore, turn.text
                from dataset
                cross join unnest(turns) t(turn)'
  ComprehendFullAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Join: 
          - ''
          - - comprehend-full-access-policy
            - -${self:provider.stage}-
            - Ref: ServicePrefix
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:Put*'
              - 's3:ListBucket'
              - 's3:Get*'
            Resource: '*'
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: '*'
              
          - Effect: Allow
            Action:
              - comprehend:Create*
              - comprehend:Describe*
              - comprehend:Batch*
              - comprehend:Delete*
              - comprehend:Detect*
              - comprehend:List*
              - comprehend:Start*
              - comprehend:Stop*
              - comprehend:ClassifyDocument
            # required for comprehend -https://docs.aws.amazon.com/comprehend/latest/dg/access-control-overview.html
            Resource: '*'
          - Effect: Allow
            Action:
              - events:Disable*
            Resource: '*'
          - Effect: Allow
            Action:
              - dynamodb:*
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:dynamodb:'
                  - Ref: AWS::Region
                  - :#{AWS::AccountId}:table/
                  - Ref: StatusTable
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - !GetAtt ComprehendDataAccessRole.Arn
              - !GetAtt TextAnalysisRole.Arn

  SnsNotificationPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Join: 
          - ''
          - - sns-notification
            - -${self:provider.stage}-
            - Ref: ServicePrefix
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sns:*
            Resource:
              - Ref: ThreatNotificationTopic
  ThreatNotificationTopic:
    Type: AWS::SNS::Topic
    Properties: 
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: email
      DisplayName:
        Fn::Join:
          - ''
          - - threat-notification
            - -${self:provider.stage}-
            - Ref: ServicePrefix
      TopicName:
        Fn::Join:
          - ''
          - - threat-notification
            - -${self:provider.stage}-
            - Ref: ServicePrefix
  S3NotificationLambdaFunction:
    DependsOn:
      - NotificationLambdaIAMRole
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json
          import logging
          import boto3
          import os

          sqs = boto3.resource('sqs')

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event,context):
            queue_name = os.environ['QUEUE_NAME']
            queue = sqs.get_queue_by_name(QueueName=queue_name)

            response = queue.send_message(MessageBody='new file received',MessageAttributes={
              'bucketName': {
                'StringValue': event['Records'][0]['s3']['bucket']['name'],
                'DataType': 'String'
              },
              'objectKey': {
                'StringValue': event['Records'][0]['s3']['object']['key'],
                'DataType': 'String'
              },
              'objectSize': {
                'StringValue': str(event['Records'][0]['s3']['object']['size']),
                'DataType': 'String'
              }
            })
            logger.info('queue response {}'.format(response))

      Environment:
        Variables:
          QUEUE_NAME: !GetAtt AudioFilesQueue.QueueName
      Handler: index.lambda_handler
      Role: !GetAtt NotificationLambdaIAMRole.Arn
      Runtime: python3.6
      Timeout: 5

  NotificationLambdaInvokePermission:
    DependsOn:
      - TranscriptionAudioFiles
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt S3NotificationLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt TranscriptionAudioFiles.Arn
  NotificationLambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketNotification
                  - s3:PutBucketNotification
                Resource: "*"
              - Effect: Allow
                Action:
                  - sqs:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
  CustomResourceLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt NotificationLambdaIAMRole.Arn
      Code:
        ZipFile: |
            from __future__ import print_function
            import json
            import boto3
            import cfnresponse
            
            print('Loading function')

            s3 = boto3.resource('s3')
            
            def lambda_handler(event, context):
                print("Received event: " + json.dumps(event, indent=2))
                responseData={}
                try:
                    if event['RequestType'] == 'Delete':
                        print("Request Type:",event['RequestType'])
                        Bucket=event['ResourceProperties']['Bucket']
                        delete_notification(Bucket)
                        print("Sending response to custom resource after Delete")
                    elif event['RequestType'] == 'Create' or event['RequestType'] == 'Update':
                        print("Request Type:",event['RequestType'])
                        LambdaArn=event['ResourceProperties']['LambdaArn']
                        Bucket=event['ResourceProperties']['Bucket']
                        add_notification(LambdaArn, Bucket)
                        responseData={'Bucket':Bucket}
                        print("Sending response to custom resource")
                    responseStatus = cfnresponse.SUCCESS
                except Exception as e:
                    print('Failed to process:', e)
                    responseStatus = cfnresponse.FAILED
                    responseData = {'Failure': 'Something bad happened.'}
                cfnresponse.send(event, context, responseStatus, responseData)

            def add_notification(LambdaArn, Bucket):
                bucket_notification = s3.BucketNotification(Bucket)
                response = bucket_notification.put(
                  NotificationConfiguration={
                    'LambdaFunctionConfigurations': [
                      {
                        'LambdaFunctionArn': LambdaArn,
                        'Events': [
                            's3:ObjectCreated:*'
                        ]
                        # 'Filter': {
                        # 'Key': {
                        #     'FilterRules': [
                        #       {
                        #         "Name": "suffix",
                        #         "Value": ".json"
                        #       }
                        #     ]
                        #   }
                        # }
                      },
                      {
                        'LambdaFunctionArn': LambdaArn,
                        'Events': [
                            's3:ObjectCreated:*'
                        ]
                        # 'Filter': {
                        # 'Key': {
                        #     'FilterRules': [
                        #       {
                        #         'Name': 'suffix',
                        #         'Value': '.wav'
                        #       }
                        #     ]
                        #   }
                        # }
                      },
                      {
                        'LambdaFunctionArn': LambdaArn,
                        'Events': [
                            's3:ObjectCreated:*'
                        ]
                        # 'Filter': {
                        # 'Key': {
                        #     'FilterRules': [
                        #       {
                        #         'Name': 'suffix',
                        #         'Value': '.txt'
                        #       }
                        #     ]
                        #   }
                        # }
                      }
                    ]
                  }
                )
                print("Put request completed....")
            
            def delete_notification(Bucket):
                bucket_notification = s3.BucketNotification(Bucket)
                response = bucket_notification.put(
                    NotificationConfiguration={}
                )
                print("Delete request completed....")
      Runtime: python3.6
      Timeout: 50

  LambdaTrigger:
    Type: Custom::LambdaTrigger
    DependsOn: NotificationLambdaInvokePermission
    Properties:
      ServiceToken: !GetAtt CustomResourceLambdaFunction.Arn
      LambdaArn: !GetAtt S3NotificationLambdaFunction.Arn
      Bucket: !Ref TranscriptionAudioFiles